name: Deploy to Production Environment

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Create .clasprc.json
        run: echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json

      - name: Create .clasp.json
        run: sed 's/__SCRIPT_ID__/${{ secrets.PRODUCTION_SCRIPT_ID }}/g' .clasp.json.template > .clasp.json

      - name: Build project
        run: npm run build

      - name: Push to Google Apps Script
        run: npx clasp push --force

      - name: Update production deployment
        id: deploy
        run: |
          sha_short=$(echo "${{ github.sha }}" | cut -c1-7)
          description="Production deployment from commit ${sha_short}"
          output=$(npx clasp deploy --deploymentId ${{ secrets.PRODUCTION_DEPLOYMENT_ID }} --description "$description")
          echo "Clasp output: $output"
          # The production URL is stable and does not change on redeploy.
          # We construct it manually for the GitHub environments tab.
          url="https://script.google.com/macros/s/${{ secrets.PRODUCTION_DEPLOYMENT_ID }}/exec"
          echo "Production URL: $url"
          echo "url=$url" >> $GITHUB_OUTPUT
